name: over_react_window
version: 1.0.0
description: A Dart interop for react-window
homepage: https://github.com/aaronlademann-wf/over_react_window
author: Aaron Lademann <aaron.lademann@workiva.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  over_react: ^2.5.2
  react: ^4.9.0
  web_skin:
    hosted:
      name: web_skin
      url: https://pub.workiva.org
    version: ^1.64.0
  web_skin_dart:
    hosted:
      name: web_skin_dart
      url: https://pub.workiva.org
    version: ^2.33.0
  w_virtual_components:
    hosted:
      name: w_virtual_components
      url: https://pub.workiva.org
    version: any

dev_dependencies:
  abide: ^1.6.4
  build_runner: ^1.7.0
  build_test: ^0.10.8
  build_web_compilers: ^2.4.0
  dart_dev: ^2.2.0
  dart_style: ^1.2.7
  dependency_validator: ^1.2.2
  over_react_test: ^2.5.1
  test: ^1.6.10
  over_react_format:
    hosted:
      name: over_react_format
      url: https://pub.workiva.org
    version: ^2.1.2


dependency_overrides:
  react:
    git:
      url: git@github.com:cleandart/react-dart.git
      ref: 9a68e7855f03e3d9e914a3952db9d43b575c6f2f # from 5.1.0-wip

